# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'abeytheo-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About Me', path: 'menu', url: 'about.html'}
- {name: 'Archive', path: 'menu', url: 'writing.html'}

# Available social icon s are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/abeytheo'}
- {icon: 'twitter', link: 'https://twitter.com/abeytheo'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/abraham-theodorus/'}
#- {icon: 'envelope', link: 'mailto:theodorus.abraham@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  previous_page: 'Older'
  next_page: 'Newer'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
